### ISSUE TITLE
Getting [Error 2] again and again

### ISSUE THREAD

**Issue by fakharunnisa95** [queenie88/A-GCN#3]
Traceback (most recent call last):
  File "demo_coco__adapt.py", line 80, in <module>
    main_coco()
  File "demo_coco__adapt.py", line 49, in main_coco
    train_dataset = COCO2014(args.data, phase='train', inp_name='data/coco/coco_glove_word2vec.pkl')
  File "/content/A-GCN/coco.py", line 114, in __init__
    download_coco2014(root, phase)
  File "/content/A-GCN/coco.py", line 40, in download_coco2014
    os.chdir(root)
FileNotFoundError: [Errno 2] No such file or directory: 'data/coco'

**Comment by queenie88** [comment]
Please check the path and download the dataset.

**Comment by queenie88** [comment]
Please, ownload the coco dataset and decompress it into this file.
